project:
  type: website
  output-dir: docs
  preview:
    port: 4200
  render: 
    - "*.qmd"

website:
  title: "Programming for QB"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: books.qmd
        text: Resources
      - href: my-background.qmd
        text: CV
      - href: contacts.qmd
        text: Contacts

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



