project:
  type: website
  output-dir: docs
  preview:
    port: 4200

website:
  title: "Quantitative Bio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: my-background.qmd
        text: CV
      - contacts.qmd

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



